### ISSUE TITLE
README example does not emit records

### ISSUE THREAD

**Issue by vlcinsky** [marselester/json-log-formatter#1]
README provides quick example of usage:

```
import logging

import json_log_formatter

formatter = json_log_formatter.JSONFormatter()

json_handler = logging.FileHandler(filename='/var/log/my-log.json')
json_handler.setFormatter(formatter)

logger = logging.getLogger('my_json')
logger.addHandler(json_handler)

logger.info('Sign up', extra={'referral_code': '52d6ce'})
```

Testing that on Debian Jessie 64-bit with Python 2.7.9 and using `JSON-log-formatter==0.0.2` there
is no output in the log file.

The reason is simple, default log level is WARN and example creates INFO log entries.

There are two options, either set log level to INFO: `logger.setLevel(logging.INFO)`  or to create log records by
    `logger.warn('Sign up', extra={'referral_code': '52d6ce'})`

**Comment by marselester** [comment]
Thank you! I have updated the README file.
