### ISSUE TITLE
How to get django.request to be in JSON format

### ISSUE THREAD

**Issue by mr337** [marselester/json-log-formatter#16]
Hi,

I am having a difficult time getting `django.requests` to be in JSON format.

After applying the below logging config to use json formatter, regular logs show up json formatted except for the requests. Has anyone encountered this?

```
[24/Nov/2020 16:58:16] "GET /api/v1/user/ HTTP/1.1" 200 374
[24/Nov/2020 16:58:32] "GET /api/v1/job/ HTTP/1.1" 200 4526                
[24/Nov/2020 16:58:35] "GET /api/v1/site/ HTTP/1.1" 200 2464 
```

Logging config:
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'json_log_formatter.JSONFormatter'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'loggers': {
        'app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

```

**Comment by marselester** [comment]
Defining `django` logger helped, for example https://github.com/marselester/django-prometheus-via-statsd/pull/1.

**Comment by marselester** [comment]
Those logs are written by`django.server` logger, see https://stackoverflow.com/questions/45972977/django-logging-requests.

**Comment by mr337** [comment]
I do not fully understand why adding `django` fixes the issue but it does work. Thanks!

**Comment by marko90b** [comment]
The issue with the `django.request` logs seems to be that the `extra` parameter includes `request`, which is not JSON serializable, causing logger to fail and returning only empty object ([`to_json()`](https://github.com/marselester/json-log-formatter/blob/master/json_log_formatter/__init__.py#L73) resorts to the last `except: return '{}'`).

It can be avoided if `request` is popped from `extra` in a custom implementation of the `json_record()`. Something like this:
```
def json_record(self, message, extra, record):
    ...
    # NOTE: request needs to be popped since it is not json serializable
    request = extra.pop('request', None)
    if request:
        # Add params from request
    ...
    return extra
```

@marselester Do you think it would be worth mentioning in the README? For me the only useable logs in production come from `django.request`.

**Comment by marselester** [comment]
@marko90b which Django version you were testing on? I tried Django v3 as shown here https://github.com/marselester/django-prometheus-via-statsd/pull/1. The `request` seems to be serialized ok, also there are tests for `WSGIRequest` https://github.com/marselester/json-log-formatter/blob/master/tests.py#L136.

```sh
$ python manage.py runserver

...

{"request": "<socket.socket fd=7, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 57218)>", "server_time": "22/Sep/2023 22:41:57", "status_code": 200, "message": "\"GET /hello HTTP/1.1\" 200 13", "time": "2023-09-22T22:41:57.828986"}
```
