### ISSUE TITLE
Django colors compatibility?

### ISSUE THREAD

**Issue by YaPeL** [marselester/json-log-formatter#21]
Hi everyone, I'm using json-log-formatter with a bunch of others third party libraries, one of them being django channels, and for some reason, it tries to print colors (but it fails to do so)

`{"message": "\u001b[33mHTTP GET /logo192.png 404 [0.73, 127.0.0.1:59720]\u001b[0m", "level": "WARNING", "module": "django.channels.server", "time": "2021-05-14T20:48:21.481139"}

{"message": "\u001b[32mHTTP GET / 302 [0.05, 127.0.0.1:59712]\u001b[0m", "level": "INFO", "module": "django.channels.server", "time": "2021-05-14T20:48:19.692535"}
`

edit: export DJANGO_COLORS="nocolor" fixes the issue, but it would be nice to support colors

**Comment by marselester** [comment]
Hi! Sorry, there are no plans to support colors in logs to keep it simple. Maybe you will find this project interesting https://github.com/xolox/python-coloredlogs. Perhaps you can use it in a [custom log formatter](https://github.com/marselester/json-log-formatter#custom-formatter).

**Comment by YaPeL** [comment]
Hey, thanks for the reply, I already have a custom formatter, the problem is that the color characters comes from the string that django channels is trying to push, like you can see [here](https://github.com/django/channels/blob/main/channels/management/commands/runserver.py#L147)
I think an easy solution would be to have a regex detect those characters, remove them, save the un-colorized message (and the string representing the colors), and then add it again once you have the full json created (characters need to be at the beginning and end of the string)

**Comment by marselester** [comment]
H! There should be other solutions, color characters shouldn't be in grep-able logs in the first place.
As you've mentioned `DJANGO_COLORS="nocolor"` solves the problem, maybe you can keep the colors enabled in a dev environment only.
Stackoverflow offers other options, for example.

> You can setup a logging StreamHandler to send logging output to streams such as sys.stdout and/or sys.stderr The handler(s) emitting to stdout/stderr can be colorised, this output exists only in a terminal window. You then setup another logging handler which sends logging output to a logfile (and does not colorise messages). https://stackoverflow.com/questions/384076/how-can-i-color-python-logging-output

I am really hesitant to make the code more complicated.
Also detecting/removing color characters might inadvertently hurt performance of somebody else's project.
Thank you for understanding.

**Comment by YaPeL** [comment]
yes, makes total sense, mine was a hacky solution, anyway, thanks for your support! I'll close this issue now.

**Comment by marselester** [comment]
no worries :)
