### ISSUE TITLE
Publish git tags on github, or a changelog

### ISSUE THREAD

**Issue by Crocmagnon** [marselester/json-log-formatter#25]
Hello!
It's currently hard to find out what's changed between two releases of this package.
Would it be possible to at least publish git tags on github so we can view commits between tags? Or better, publish a changelog, but I reckon that would require more work for the maintainers.

Thanks 🙂

**Comment by marselester** [comment]
Hi! I've added the missing tags, sorry for inconvenience.

**Comment by Crocmagnon** [comment]
Thanks !
