### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [marselester/json-log-formatter#26]
Ref : https://www.python.org/dev/peps/pep-0632/#migration-advice

`setup` from setuptools can be used.

https://github.com/marselester/json-log-formatter/blob/a66df694e1deeb4c918b186ea298c69f775c14af/setup.py#L1

**Comment by marselester** [comment]
Hi, thank you! I have updated the `setup.py`.

> Code that imports distutils will no longer work from Python 3.12.
