### ISSUE TITLE
utcnow usage is deprecated

### ISSUE THREAD

**Issue by pwrmiller** [marselester/json-log-formatter#32]
Python 3.12 is deprecating the use of `datetime.datetime.utcnow()`

Since a number of packages people use might be referencing this repository as a transitive dependency and because this project uses `datetime.utcnow()` to create a naive timestamp, can we consider moving the code that generates the extra field `extra['time']` in L123 of `__init__.py` to use `datetime.datetime.now(datetime.timezone.utc)`? 

This would likely represent a "major version" bump if you're using semver, as you'd be dropping support for 2.7. There may be alternatives, such as using pytz or even writing a simple UTC class for 2.7 compatibility.

**Comment by marselester** [comment]
I have created a PR https://github.com/marselester/json-log-formatter/pull/33 to address the issue, thank you.
