### ISSUE TITLE
Log level not factored into json

### ISSUE THREAD

**Issue by GM12Tick** [marselester/json-log-formatter#6]
Log Level, Logger name and more are not formatted into the JSON.
I think the fix should be inside "json_record" method.

If a configuration is wanted , its possible to define a constructor to the json_log_formatting to pass options to it. WDYT?

Will submit a pull request later today / tomorrow for the Log level at least.

**Comment by marselester** [comment]
Hi Yechiel,

Thank you for the contribution.

However, I kept default logging payload small intentionally so it suits more use cases.
For example, a developer wants to log user sign ins/ups, and not interested in log level information
(something like an audit log).

When a developer needs to [log more info](https://github.com/marselester/json-log-formatter#custom-formatter), she can overwrite `json_record()` method.

From my perspective the library provides minimal but sufficient functionality to log in JSON format.

Regards,
Marsel
