### ISSUE TITLE
Include bultin attributes in JSON

### ISSUE THREAD

**Issue by jzalger** [marselester/json-log-formatter#8]
How do we include built-in attributes such as the logger name and log level into the json message? Do these have to be specified explicitly in the 'extra' dict?

**Comment by jzalger** [comment]
Not sure if this was indended, but I was able to do it by overriding the `json_record()` method and adding some of the builtins into the extra dictionary.

**Comment by marselester** [comment]
Hi Jonathan, you're right, `json_record()` is a proper place to define custom "default" fields to log as it's suggested in [the docs](https://github.com/marselester/json-log-formatter#custom-formatter).

**Comment by januszm** [comment]
level is such a basic attribute that it's a bit hard to understand why it would need to be added as custom? this should definitely be included in the standard formatter call

**Comment by marselester** [comment]
Hi Janusz, there was a similar question answered here https://github.com/marselester/json-log-formatter/issues/6#issuecomment-289354937.

The idea of separating a log level from a basic logger is not something unheard of, e.g., Go kit implements leveled logging on top of the log package https://pkg.go.dev/github.com/go-kit/log/level.

**Comment by januszm** [comment]
Thanks @marselester , I think the key part of your response is about use cases.

> default logging payload small intentionally so it suits more use cases.

In my personal opinion, the lack of log severity just doesn't cover most use cases. I think most teams in their projects are looking for plug-and-play solutions that will just work, with possible additional configuration. In this case, we are missing something that virtually every log collection and analysis system requires, like Datadog (https://docs.datadoghq.com/logs/log_collection/python/?tab=jsonlogformatter).

The redefinition of the entire formatter class is not a minor change to the configuration (such as passing `'levelname': True`). Anyway, in my projects I have already redefined the formatter class and each time the only change was adding the `levelname` attribute.

Perhaps just adding one more extended formatter class to this project would be a solution, something (let's call it `JSONFormatterExt`) that inherits from JSONFormatter and adds the necessary attributes to run on a production server system, if that's something that could potentially be included in for this project, I can prepare a PR

**Comment by marselester** [comment]
Good point! Can you please check if the following built-in attributes are sufficient https://github.com/marselester/json-log-formatter/pull/22?

**Comment by marselester** [comment]
I have published `0.4.0` release with the requested change.

**Comment by januszm** [comment]
Thank you!
